# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Clinic Check in' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire'
pod 'SwiftyJSON'
pod 'AlamofireImage', '~> 3.0'
pod 'MRCountryPicker', '~> 0.0.7'
pod 'PopupDialog', '~> 0.7'
pod 'Toast-Swift', '~> 3.0.1'
pod 'Toaster'
  # Pods for Clinic Check in

  target 'Clinic Check inTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Clinic Check inUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
